apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devhire-api
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: devhire-cloud
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: devhire.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
