apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devhire
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.example.yaml
  - services.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - quota.yaml
images:
  - name: devhire/api-gateway
    newName: ghcr.io/jasontm17/devhire/api-gateway
    newTag: sha-REPLACE_WITH_GIT_SHA
  - name: devhire/auth-service
    newName: ghcr.io/jasontm17/devhire/auth-service
    newTag: sha-REPLACE_WITH_GIT_SHA
  - name: devhire/user-service
    newName: ghcr.io/jasontm17/devhire/user-service
    newTag: sha-REPLACE_WITH_GIT_SHA
  - name: devhire/company-service
    newName: ghcr.io/jasontm17/devhire/company-service
    newTag: sha-REPLACE_WITH_GIT_SHA
  - name: devhire/job-service
    newName: ghcr.io/jasontm17/devhire/job-service
    newTag: sha-REPLACE_WITH_GIT_SHA
  - name: devhire/application-service
    newName: ghcr.io/jasontm17/devhire/application-service
    newTag: sha-REPLACE_WITH_GIT_SHA
  - name: devhire/notification-service
    newName: ghcr.io/jasontm17/devhire/notification-service
    newTag: sha-REPLACE_WITH_GIT_SHA
  - name: devhire/audit-service
    newName: ghcr.io/jasontm17/devhire/audit-service
    newTag: sha-REPLACE_WITH_GIT_SHA
  - name: devhire/ai-service
    newName: ghcr.io/jasontm17/devhire/ai-service
    newTag: sha-REPLACE_WITH_GIT_SHA
  - name: devhire/assessment-runner-service
    newName: ghcr.io/jasontm17/devhire/assessment-runner-service
    newTag: sha-REPLACE_WITH_GIT_SHA
  - name: devhire/frontend
    newName: ghcr.io/jasontm17/devhire/frontend
    newTag: sha-REPLACE_WITH_GIT_SHA
