apiVersion: v1
kind: ServiceAccount
metadata:
  name: devhire-service
  labels:
    app.kubernetes.io/name: devhire-cloud
    app.kubernetes.io/part-of: devhire-cloud
automountServiceAccountToken: false
