apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devhire.configName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "devhire.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.global.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
