{{- if .Values.externalSecrets.enabled }}
{{- if .Values.externalSecrets.secretStore.create }}
apiVersion: external-secrets.io/v1beta1
kind: {{ .Values.externalSecrets.secretStore.kind }}
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
{{- if ne .Values.externalSecrets.secretStore.kind "ClusterSecretStore" }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  labels:
{{ include "devhire.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.aws.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.global.serviceAccountName }}
            namespace: {{ .Values.global.namespace }}
---
{{- end }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "devhire.secretName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "devhire.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: {{ include "devhire.secretName" . }}
    creationPolicy: Owner
  data:
{{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey | quote }}
{{- if .property }}
        property: {{ .property | quote }}
{{- end }}
{{- end }}
{{- end }}
