{{- if .Values.secrets.createExample }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devhire.secretName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "devhire.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets.stringData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
