{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
{{ include "devhire.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
spec:
  type: ClusterIP
  selector:
{{ include "devhire.selectorLabels" (dict "name" $name) | nindent 4 }}
  ports:
    - name: http
      port: {{ $service.port }}
      targetPort: http
---
{{- end }}
{{- end }}
