package com.devhire.notification.email;

import com.devhire.notification.config.EmailProperties;
import com.devhire.notification.entity.Notification;
import org.springframework.stereotype.Component;

@Component
public class EmailTemplateRenderer {
    private final EmailProperties properties;

    public EmailTemplateRenderer(EmailProperties properties) {
        this.properties = properties;
    }

    public EmailMessage render(Notification notification, String recipient) {
        String ctaUrl = properties.dashboardBaseUrl() + "/notifications";
        String accent = switch (notification.getType()) {
            case "APPLICATION_SUBMITTED" -> "#2563eb";
            case "APPLICATION_STATUS_CHANGED" -> "#16a34a";
            default -> "#334155";
        };
        String html = """
                <!doctype html>
                <html lang="en">
                  <body style="margin:0;background:#f8fafc;font-family:Arial,Helvetica,sans-serif;color:#0f172a">
                    <table role="presentation" width="100%%" cellspacing="0" cellpadding="0" style="background:#f8fafc;padding:32px 0">
                      <tr>
                        <td align="center">
                          <table role="presentation" width="100%%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#ffffff;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden">
                            <tr>
                              <td style="padding:20px 24px;background:%s;color:#ffffff">
                                <div style="font-size:14px;font-weight:700;letter-spacing:0">DevHire Cloud</div>
                              </td>
                            </tr>
                            <tr>
                              <td style="padding:28px 24px">
                                <h1 style="margin:0 0 12px;font-size:22px;line-height:1.3;color:#0f172a">%s</h1>
                                <p style="margin:0 0 24px;font-size:15px;line-height:1.7;color:#334155">%s</p>
                                <a href="%s" style="display:inline-block;background:%s;color:#ffffff;text-decoration:none;font-weight:700;border-radius:6px;padding:12px 18px">Open notification</a>
                              </td>
                            </tr>
                            <tr>
                              <td style="padding:16px 24px;border-top:1px solid #e2e8f0;color:#64748b;font-size:12px;line-height:1.6">
                                This message was generated by DevHire Cloud. If you did not expect it, you can safely ignore it.
                              </td>
                            </tr>
                          </table>
                        </td>
                      </tr>
                    </table>
                  </body>
                </html>
                """.formatted(accent, escape(notification.getTitle()), escape(notification.getMessage()), ctaUrl, accent);
        String text = notification.getTitle() + System.lineSeparator()
                + notification.getMessage() + System.lineSeparator()
                + "Open notification: " + ctaUrl;
        return new EmailMessage(recipient, "[DevHire Cloud] " + notification.getTitle(), html, text);
    }

    private static String escape(String value) {
        if (value == null) {
            return "";
        }
        return value.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;");
    }
}
