apiVersion: v2
name: devhire-cloud
description: Production-style Helm chart for DevHire Cloud microservices recruitment platform.
type: application
version: 0.6.0
appVersion: "0.5.1"
keywords:
  - java
  - spring-boot
  - microservices
  - recruitment
  - portfolio
maintainers:
  - name: JasonTM17
    url: https://github.com/JasonTM17
