[CmdletBinding()]
param(
    [string]$GatewayUrl = $(if ($env:E2E_GATEWAY_URL) { $env:E2E_GATEWAY_URL } else { "http://localhost:8080" }),
    [string]$MailpitUrl = $(if ($env:MAILPIT_URL) { $env:MAILPIT_URL } else { "http://localhost:8025" }),
    [int]$TimeoutSeconds = 120
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Wait-HttpOk {
    param(
        [Parameter(Mandatory = $true)][string]$Url,
        [int]$TimeoutSeconds = 120
    )

    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    do {
        try {
            $response = Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec 10
            if ($response.StatusCode -ge 200 -and $response.StatusCode -lt 500) {
                return
            }
        } catch {
            Start-Sleep -Seconds 3
        }
    } while ((Get-Date) -lt $deadline)

    throw "Timed out waiting for $Url"
}

function Invoke-Api {
    param(
        [Parameter(Mandatory = $true)][ValidateSet("GET", "POST", "PATCH")][string]$Method,
        [Parameter(Mandatory = $true)][string]$Path,
        [string]$Token,
        $Body = $null
    )

    $headers = @{}
    if (-not [string]::IsNullOrWhiteSpace($Token)) {
        $headers.Authorization = "Bearer $Token"
    }

    $params = @{
        Method     = $Method
        Uri        = "$GatewayUrl$Path"
        Headers    = $headers
        TimeoutSec = 30
    }
    if ($null -ne $Body) {
        $params.ContentType = "application/json"
        $params.Body = ($Body | ConvertTo-Json -Depth 12)
    }

    $response = Invoke-RestMethod @params
    if ($response.PSObject.Properties.Name -contains "data") {
        return $response.data
    }
    return $response
}

function Login {
    param(
        [Parameter(Mandatory = $true)][string]$Email,
        [Parameter(Mandatory = $true)][string]$Password
    )

    $response = Invoke-Api -Method POST -Path "/api/auth/login" -Body @{
        email    = $Email
        password = $Password
    }
    if ([string]::IsNullOrWhiteSpace($response.accessToken)) {
        throw "Login for $Email did not return an access token"
    }
    return $response.accessToken
}

function Get-MailpitMessageCount {
    $response = Invoke-RestMethod -Uri "$MailpitUrl/api/v1/messages?limit=100" -TimeoutSec 15
    foreach ($property in @("total", "Total", "count", "Count")) {
        if ($response.PSObject.Properties.Name -contains $property) {
            return [int]$response.$property
        }
    }
    foreach ($property in @("messages", "Messages")) {
        if ($response.PSObject.Properties.Name -contains $property) {
            return @($response.$property).Count
        }
    }
    return 0
}

function Get-MailpitMessagesJson {
    $response = Invoke-RestMethod -Uri "$MailpitUrl/api/v1/messages?limit=100" -TimeoutSec 15
    return ($response | ConvertTo-Json -Depth 20)
}

Wait-HttpOk -Url "$GatewayUrl/actuator/health/readiness" -TimeoutSeconds $TimeoutSeconds
Wait-HttpOk -Url "$MailpitUrl/readyz" -TimeoutSeconds $TimeoutSeconds

$before = Get-MailpitMessageCount

$adminToken = Login -Email "admin@devhire.local" -Password "Admin@123456"
$employerToken = Login -Email "employer@devhire.local" -Password "Employer@123456"
$candidateToken = Login -Email "candidate@devhire.local" -Password "Candidate@123456"

$stamp = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
$company = Invoke-Api -Method POST -Path "/api/companies" -Token $employerToken -Body @{
    name        = "DevHire Email Smoke $stamp"
    logoUrl     = "https://cdn.devhire.local/logos/mailpit.png"
    website     = "https://devhire.local"
    size        = "51-200"
    industry    = "Software"
    description = "Generated by Mailpit email smoke verification."
}
$company = Invoke-Api -Method PATCH -Path "/api/admin/companies/$($company.id)/approve" -Token $adminToken

$job = Invoke-Api -Method POST -Path "/api/jobs" -Token $employerToken -Body @{
    companyId    = $company.id
    title        = "Senior Java Mailpit Smoke $stamp"
    description  = "Verify DevHire notification email is captured by Mailpit."
    requirements = "Java 21, Spring Boot, Kafka, PostgreSQL"
    benefits     = "Production-like email evidence without external SMTP"
    salaryMin    = 3500
    salaryMax    = 6500
    location     = "Ho Chi Minh City"
    level        = "Senior"
    type         = "FULL_TIME"
    skills       = @("Java", "Kafka", "Email")
}
$null = Invoke-Api -Method PATCH -Path "/api/jobs/$($job.id)/submit-review" -Token $employerToken
$job = Invoke-Api -Method PATCH -Path "/api/admin/jobs/$($job.id)/approve" -Token $adminToken
$application = Invoke-Api -Method POST -Path "/api/jobs/$($job.id)/applications" -Token $candidateToken -Body @{
    cvUrl       = "https://cdn.devhire.local/cv/mailpit-smoke.pdf"
    coverLetter = "Generated by Mailpit email smoke verification."
}
$null = Invoke-Api -Method PATCH -Path "/api/applications/$($application.id)/status" -Token $employerToken -Body @{
    status = "INTERVIEW"
    note   = "Mailpit email smoke status update"
}

$deadline = (Get-Date).AddSeconds($TimeoutSeconds)
do {
    Start-Sleep -Seconds 5
    $after = Get-MailpitMessageCount
    $messagesJson = Get-MailpitMessagesJson
    if ($after -gt $before -and $messagesJson -match [regex]::Escape($job.title)) {
        [pscustomobject]@{
            status       = "passed"
            beforeCount  = $before
            afterCount   = $after
            mailpitUrl   = $MailpitUrl
            jobTitle     = $job.title
            applicationId = $application.id
        } | ConvertTo-Json -Depth 5
        return
    }
} while ((Get-Date) -lt $deadline)

throw "Mailpit did not capture an expected DevHire notification email for '$($job.title)' within $TimeoutSeconds seconds."
